name = "anasy-ads"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL = "/dashboard"
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL = "/dashboard"
NEXT_PUBLIC_APP_URL = "https://anasy-ads.adm-b11.workers.dev"
